#!/bin/sh -xe

# This script assumes all source database files are unencrypted
# and assumes sqlite3 is already installed

sqlite3 --version

srcdir=~/dev/local/wingeneal/shared/FTM_DOCUMENTS

ts=$(date +%Y%m%d_%H%M%S)
bakdir=/srv/arc/geneal/backups/family_tree_maker/$ts
mkdir $bakdir

gitdir=~/dev/github_cmosher01/family-tree-maker-data-private



cd $srcdir
for db in *.ftm ; do
    cp "${db}" "$bakdir/${db}"
done
cd -



cd $bakdir

for db in *.ftm ; do
    sqlite3 "${db}" "UPDATE MediaFile SET Thumbnail = NULL;"
    sqlite3 "${db}" ".selftest --init"
    # to verify later run:
    # sqlite> .selftest
    # Tests generated by --init
    # 0 errors out of 49 tests

    echo "/*" >"${db}.sql"
    echo "backup timestamp: $ts" >>"${db}.sql"
    sqlite3 "${db}" .databases .tables .dbinfo >>"${db}.sql"
    echo "*/" >>"${db}.sql"

    sqlite3 "${db}" .dump | sed 's/localized_caseinsensitive/NOCASE/' >>"${db}.sql"

    cp -v "${db}.sql" "${gitdir}/"
done

dos2unix *.sql
dos2unix -ih *.sql
pwd
ls -lh --full-time --color

cd -
