#!/bin/sh -e

# This script assumes all source database files are unencrypted
# and assumes sqlite3,dos2unix,rsync are already installed



# RECOMMENDED PROCESS
# Patch FTM to work exclusively with unencrypted files.
# Use Windows in a VM to update FTM files in the srcdir (define below), a shared directory between Windows and this host
# Make any changes
# synchoronize with Ancestry.com
# QUIT THE WINDOWS VM
# Manually examine the shared directory for foul play (e.g., ransome-ware)
# Run this script, which first runs a sanity check on the *.ftm files, and aborts if any are corrupt
# If all *.ftm files are readable, this script make an rsync copy to bakdir (define below), and
# extracts text SQL files of each tree and copies it to the gitdir (define below)

# MAKE SURE bakdir is not reachable by (i.e., shared with) the Windows VM



sqlite3 --version
dos2unix --version
rsync --version
ftm-fixer --version

srcdir=~/SAVE/shared/ftm
bakdir=~/SAVE/ftm_backup
gitdir=~/dev/github_cmosher01/family-tree-maker-data



cd $srcdir

# make sure there is at least one *.ftm file
(( cFtm = $(ls *.ftm | wc -l) ))
if (( cFtm <= 0 )) ; then
    echo "no files found"
    exit 1
fi
echo "$cFtm files found..."

# go through all *.ftm files and do a sanity check to be sure they are actually SQLite databases
for db in $(find . -name \*.ftm | sort -f) ; do
    echo "${db}"
    sqlite3 "${db}" ".databases"
done
echo "============================================================="
cd -





# full backup
mkdir -p $bakdir
rsync -ltvihPr $srcdir/ $bakdir/
echo "============================================================="



ftm-fixer --force $srcdir/*.ftm



# make .sql files (in temp work area) and copy to gitdir
tmpdir=$(mktemp -d)
rsync -ltvihPr --include='*.ftm' --exclude='*' $srcdir/ $tmpdir/
cd $tmpdir
for db in *.ftm ; do
    sqlite3 "${db}" "UPDATE MediaFile SET Thumbnail = NULL;"
    sqlite3 "${db}" ".selftest --init"
    # to verify later run:
    # sqlite> .selftest
    # Tests generated by --init
    # 0 errors out of 49 tests

    echo "/*" >"${db}.sql"
    sqlite3 "${db}" .tables >>"${db}.sql"
    echo "*/" >>"${db}.sql"

    sqlite3 "${db}" .dump | sed 's/localized_caseinsensitive/NOCASE/' >>"${db}.sql"
    dos2unix "${db}.sql"
    dos2unix -ih "${db}.sql"

    cp -v "${db}.sql" "${gitdir}/"
done
echo "============================================================="
cd -



rsync -ltvihPr --super --stats $srcdir/ rsync://user@mosher.mine.nu:/srv/ftm/



echo "tmp   : $tmpdir"
echo "from  : $srcdir"
echo "backup: $bakdir"
echo "SQL   : $gitdir"
